<?php
/**
 * SmartOffice Connector — Auto-login handler.
 *
 * Intercepts ?smartoffice_login=<token> requests and authenticates the user
 * using a one-time token generated by the REST API.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class SmartOffice_Auto_Login {

    /**
     * Hook into WordPress init to check for login tokens.
     */
    public static function init() {
        // Run very early — before template loading
        add_action( 'template_redirect', [ __CLASS__, 'handle_login_token' ], 1 );
    }

    /**
     * If ?smartoffice_login is present, validate and auto-login.
     */
    public static function handle_login_token() {
        if ( empty( $_GET['smartoffice_login'] ) ) {
            return;
        }

        // Sanitize token — must be exactly 64 hex characters
        $token = sanitize_text_field( $_GET['smartoffice_login'] );
        if ( ! preg_match( '/^[a-f0-9]{64}$/', $token ) ) {
            wp_die(
                esc_html__( 'Invalid login token format.', 'smartoffice-connector' ),
                esc_html__( 'Login Failed', 'smartoffice-connector' ),
                [ 'response' => 403 ]
            );
        }

        // Retrieve token data
        $transient_key = 'smartoffice_token_' . $token;
        $token_data    = get_transient( $transient_key );

        if ( ! $token_data ) {
            wp_die(
                esc_html__( 'Login token is invalid or has expired.', 'smartoffice-connector' ),
                esc_html__( 'Login Failed', 'smartoffice-connector' ),
                [ 'response' => 403 ]
            );
        }

        // Delete immediately — one-time use
        delete_transient( $transient_key );

        // Verify IP binding if enabled
        $ip_binding = get_option( 'smartoffice_ip_binding', 'yes' );
        if ( $ip_binding === 'yes' && ! empty( $token_data['ip'] ) ) {
            $current_ip = SmartOffice_REST_API::get_client_ip();
            // Compare the SmartOffice server IP (who requested the token)
            // with the browser IP (who is using the token).
            // Note: In typical setups both go through the same office network,
            // but if SmartOffice runs on a different server, disable IP binding
            // or this check will fail. We log a warning but allow it when IPs
            // come from the same /24 subnet, or when the token was generated
            // from a private IP (server-to-server).
            if ( $current_ip !== $token_data['ip'] ) {
                // Allow if the server IP is private (server-to-server call)
                if ( ! self::is_private_ip( $token_data['ip'] ) ) {
                    self::log_failed_login( $token_data, $current_ip, 'IP mismatch' );
                    wp_die(
                        esc_html__( 'Login token cannot be used from this network.', 'smartoffice-connector' ),
                        esc_html__( 'Login Failed', 'smartoffice-connector' ),
                        [ 'response' => 403 ]
                    );
                }
            }
        }

        // Validate the user still exists and has admin capabilities
        $user_id = (int) $token_data['user_id'];
        $user    = get_user_by( 'id', $user_id );

        if ( ! $user || ! user_can( $user, 'manage_options' ) ) {
            wp_die(
                esc_html__( 'The configured admin account is no longer valid.', 'smartoffice-connector' ),
                esc_html__( 'Login Failed', 'smartoffice-connector' ),
                [ 'response' => 500 ]
            );
        }

        // Authenticate
        wp_set_auth_cookie( $user_id, false, is_ssl() );
        wp_set_current_user( $user_id );

        // Audit log
        self::log_successful_login( $token_data );

        // Redirect to admin dashboard
        wp_safe_redirect( admin_url() );
        exit;
    }

    /**
     * Record a successful auto-login in the login log (last 50 entries).
     */
    private static function log_successful_login( array $token_data ) {
        $log   = get_option( 'smartoffice_login_log', [] );
        $log[] = [
            'requester' => $token_data['requester'] ?? 'Unknown',
            'ip'        => SmartOffice_REST_API::get_client_ip(),
            'server_ip' => $token_data['ip'] ?? '',
            'time'      => current_time( 'mysql' ),
            'status'    => 'success',
        ];

        // Keep last 50 entries
        if ( count( $log ) > 50 ) {
            $log = array_slice( $log, -50 );
        }

        update_option( 'smartoffice_login_log', $log, false );
    }

    /**
     * Record a failed auto-login attempt.
     */
    private static function log_failed_login( array $token_data, string $actual_ip, string $reason ) {
        $log   = get_option( 'smartoffice_login_log', [] );
        $log[] = [
            'requester' => $token_data['requester'] ?? 'Unknown',
            'ip'        => $actual_ip,
            'server_ip' => $token_data['ip'] ?? '',
            'time'      => current_time( 'mysql' ),
            'status'    => 'failed',
            'reason'    => $reason,
        ];

        if ( count( $log ) > 50 ) {
            $log = array_slice( $log, -50 );
        }

        update_option( 'smartoffice_login_log', $log, false );
    }

    /**
     * Check if an IP is in a private range (server-to-server calls).
     */
    private static function is_private_ip( string $ip ): bool {
        return ! filter_var(
            $ip,
            FILTER_VALIDATE_IP,
            FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE
        );
    }
}
